# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name': 'CostCenter', 'verbose_name_plural': 'CostCenters'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='parttype',
            options={'verbose_name': 'PartType', 'verbose_name_plural': 'PartTypes'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'WorkType', 'verbose_name_plural': 'WorkTypes'},
        ),
    ]
