# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-11-14 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.Role', verbose_name='Role'),
        ),
    ]
