# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 10:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0002_auto_20161122_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
            options={
                'verbose_name': 'WorkPattern',
                'verbose_name_plural': 'WorkPatterns',
            },
        ),
        migrations.CreateModel(
            name='WorkPatternGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('child_order', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('child_groups', models.ManyToManyField(blank=True, related_name='_workpatterngroup_child_groups_+', to='benteler.WorkPatternGroup')),
                ('child_patterns', models.ManyToManyField(blank=True, to='benteler.WorkPattern')),
            ],
            options={
                'verbose_name': 'WorkPatternGroup',
                'verbose_name_plural': 'WorkPatternGroups',
            },
        ),
        migrations.AddField(
            model_name='workpattern',
            name='child_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkPatternGroup'),
        ),
        migrations.AddField(
            model_name='workpattern',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkType'),
        ),
    ]
