# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 12:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0003_auto_20170108_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='DateStart')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='DateEnd')),
                ('relevance', models.BooleanField(verbose_name='Relevance')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('child_order', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='ChildOrder')),
                ('visibility', models.BooleanField(verbose_name='Visibility')),
                ('child_groups', models.ManyToManyField(blank=True, related_name='_workgroup_child_groups_+', to='benteler.WorkGroup', verbose_name='ChildWorkGroups')),
                ('child_works', models.ManyToManyField(blank=True, to='benteler.Work', verbose_name='ChildWorks')),
            ],
            options={
                'verbose_name': 'WorkGroup',
                'verbose_name_plural': 'WorkGroups',
            },
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='num',
            field=models.IntegerField(verbose_name='Num'),
        ),
        migrations.AlterField(
            model_name='part',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.PartType', verbose_name='PartType'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.CostCenter', verbose_name='CostCenter'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='parts',
            field=models.ManyToManyField(to='benteler.Part', verbose_name='Parts'),
        ),
        migrations.AlterField(
            model_name='place',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='SerialNumber'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='CreateTime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.Role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, verbose_name='UserName'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='child_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkPatternGroup', verbose_name='ChildGroup'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='duration',
            field=models.IntegerField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='period',
            field=models.IntegerField(verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='workpattern',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkType', verbose_name='WorkType'),
        ),
        migrations.AlterField(
            model_name='workpatterngroup',
            name='child_groups',
            field=models.ManyToManyField(blank=True, related_name='_workpatterngroup_child_groups_+', to='benteler.WorkPatternGroup', verbose_name='ChildPatternGroups'),
        ),
        migrations.AlterField(
            model_name='workpatterngroup',
            name='child_order',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='ChildOrder'),
        ),
        migrations.AlterField(
            model_name='workpatterngroup',
            name='child_patterns',
            field=models.ManyToManyField(blank=True, to='benteler.WorkPattern', verbose_name='ChildPatterns'),
        ),
        migrations.AlterField(
            model_name='workpatterngroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkType', verbose_name='ParentWorkType'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='pattern_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkPatternGroup', verbose_name='WorkPatternGroup'),
        ),
        migrations.AddField(
            model_name='work',
            name='child_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkGroup', verbose_name='ChildGroup'),
        ),
        migrations.AddField(
            model_name='work',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='benteler.Part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='work',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.Place', verbose_name='Place'),
        ),
        migrations.AddField(
            model_name='work',
            name='responsibles',
            field=models.ManyToManyField(to='benteler.User', verbose_name='Responsibles'),
        ),
        migrations.AddField(
            model_name='work',
            name='work_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.WorkPattern', verbose_name='WorkPattern'),
        ),
    ]
