# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0005_auto_20170108_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='relevance',
            field=models.BooleanField(default=True, verbose_name='Relevance'),
        ),
    ]
