# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0006_auto_20170108_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executors', models.ManyToManyField(to='benteler.User', verbose_name='Executors')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'EventStatus',
                'verbose_name_plural': 'EventStatuses',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.EventStatus', verbose_name='EventStatus'),
        ),
        migrations.AddField(
            model_name='event',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benteler.Work', verbose_name='Work'),
        ),
    ]
