# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benteler', '0007_auto_20170108_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
